[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "solar-flare-finder"
version = "0.1.0"
description = "Statistics of multi-instrument observations of solar flares"
authors = [{ name = "James Kavanagh-Cranston" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "astropy",
    "sunpy[net]",
    "fastapi",
    "uvicorn",
    "sqlalchemy>=2.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "black",
    "ruff",
    "sphinx",
    "sphinx-rtd-theme",
    "sunpy[all]",
]
doc = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx_rtd_dark_mode",
]

[project.scripts]
solar-flare-finder = "solar_flare_finder.cli:main"

[tool.setuptools]
packages = ["solar_flare_finder"]

[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'
