#!/bin/tcsh
# simple script to run SSWIDL

# configure IDL
source /opt/harris/idl/bin/idl_setup

# configure the IDL_PATH
setenv IDL_PATH "+$HOME/idl::<IDL_DEFAULT>"

# add in the idllibs folders
setenv IDL_PATH "+/opt/idllibs/:$IDL_PATH"

# SSW environment variables
setenv SSW /opt/ssw
setenv SSW_INSTR "aia hmi eve sumer chianti eis eit cds trace mdi sot xrt iris hessi trace hxrs nso vso goes secchi spex xray yohkoh ontology stereo mjastereo"
source $SSW/gen/setup/setup.ssw /quiet

#actually run SSWIDL
sswidl

exit 0
