version: "3.9"

services:
  flare-updater:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VERSION: ${VERSION}  # will come from environment
    container_name: solar_flare_finder_updater
    command: update
    volumes:
      - flare_data:/app/data
    restart: "no"

  flare-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VERSION: ${VERSION}  # will come from environment
    container_name: solar_flare_finder_web
    command: web
    ports:
      - "8000:8000"
    volumes:
      - flare_data:/app/data
    depends_on:
      - flare-updater

volumes:
  flare_data:
    driver: local
